/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package painting;

import java.awt.Color;
import java.awt.Point;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JTextField;
import shapes.Line;


/**
 *
 * @author yasmi
 */
public class NewLine extends javax.swing.JFrame implements Node,AddingWindows{
    private Node parent;
    private Color color= Color.BLACK;
    private  Line line;
    private JComboBox shapesBox;
    private MyPanel myPanel;
    /**
     * Creates new form newLine
     */
     public NewLine(){
        
    }
    public NewLine(JComboBox shapesBox, MyPanel myPanel) {
        initComponents();
        this.shapesBox = shapesBox;
        this.myPanel = myPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectColor = new java.awt.Button();
        createLine = new java.awt.Button();
        y2TextField = new javax.swing.JTextField();
        x1TextField = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        label5 = new java.awt.Label();
        x2TextField = new javax.swing.JTextField();
        label2 = new java.awt.Label();
        label6 = new java.awt.Label();
        y1TextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        selectColor.setBackground(new java.awt.Color(51, 51, 51));
        selectColor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        selectColor.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        selectColor.setForeground(new java.awt.Color(255, 255, 255));
        selectColor.setLabel("select color");
        selectColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectColorActionPerformed(evt);
            }
        });

        createLine.setBackground(new java.awt.Color(0, 0, 0));
        createLine.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        createLine.setForeground(new java.awt.Color(255, 255, 255));
        createLine.setLabel("create line");
        createLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createLineActionPerformed(evt);
            }
        });

        x1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x1TextFieldActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setName(""); // NOI18N
        label1.setText("X1");

        label5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label5.setName(""); // NOI18N
        label5.setText("X2");

        x2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x2TextFieldActionPerformed(evt);
            }
        });

        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("Y2");

        label6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label6.setName(""); // NOI18N
        label6.setText("Y1");

        y1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y1TextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(4, 4, 4))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectColor, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(createLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(y2TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(x1TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(x2TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(y1TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(x1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(y1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(x2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(y2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selectColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectColorActionPerformed
        // TODO add your handling code here:
        color = JColorChooser.showDialog(null, "Choose border color", Color.BLACK);
    }//GEN-LAST:event_selectColorActionPerformed

    private void createLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createLineActionPerformed
        // TODO add your handling code here:
        if(validation(jTextFields())){
            this.setVisible(false);
            ((JFrame)getParentNode()).setVisible(true);
            int[]arr = getTextFields();
            Point p1 = new Point(arr[0], arr[1]);
            Point p2 = new Point(arr[2],arr[3]);
            line= new Line(++MiniPaint.counter, p1,p2);
            line.setColor(color);
            myPanel.addShape(line);
            shapesBox.addItem(line);
           // line.draw(myPanel.getGraphics());
            myPanel.refresh(myPanel.getGraphics());

        }
        
    }//GEN-LAST:event_createLineActionPerformed

    private void x1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x1TextFieldActionPerformed

    private void x2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x2TextFieldActionPerformed

    private void y1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y1TextFieldActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        clearTextField();
        this.setVisible(false);
        ((JFrame)getParentNode()).setVisible(true);
    }//GEN-LAST:event_formWindowClosing


        
    @Override
        public boolean validation(JTextField[] textFields){
        for (JTextField textField : textFields) {
            if (isValid(textField) == false) {
                return false;
            }
        }
         return true;
        }
          
    @Override
        public boolean isValid(JTextField textField){ //handle floating point
        String number = textField.getText();
        if(number.isBlank()){ //empty
            textField.setText("Enter Data");
            return false;
        }
        if(number.contains("-")){
            textField.setText("+ve Data");
            return false; //-ve number
        }
         for (int i = 0; i < number.length(); i++){
             if (Character.isDigit((number.charAt(i))) == false){
                 textField.setText("non numeric");
                   return false;
             }
         } //when one non numeric value is found, return false
         
             return true;
    }
     @Override
        public String[] textFields(){
            String[ ] str = new String[4];
            str[0]= x1TextField.getText();
            str[1]= y1TextField.getText();
            str[2]= x2TextField.getText();
            str[3]= y2TextField.getText();
            
           return str;
        } 
    @Override
        public  JTextField[] jTextFields(){
            JTextField[] arr = new JTextField[4];
            arr[0]= x1TextField;
            arr[1]= y1TextField;
            arr[2]= x2TextField;
            arr[3]= y2TextField;
            return arr;
        }  
        
         @Override
    public int[] getTextFields() {
        String[]str = textFields();
        int[] arr = new int[4];
        for(int i = 0; i<textFields().length;i++){
            arr[i]= Integer.parseInt(str[i]);
        }
        
       return arr;
    }
        @Override
    public void clearTextField(){
        x1TextField.setText("");
        y1TextField.setText("");
        x2TextField.setText("");
        y2TextField.setText("");
        
    }


     @Override
    public Node getParentNode() {
        return parent;
    }
    @Override
    public void setParentNode(Node node) {
        this.parent = node;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewLine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewLine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewLine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewLine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewLine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button createLine;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Button selectColor;
    private javax.swing.JTextField x1TextField;
    private javax.swing.JTextField x2TextField;
    private javax.swing.JTextField y1TextField;
    private javax.swing.JTextField y2TextField;
    // End of variables declaration//GEN-END:variables
}
